import React from 'react'

import styles from "../../../styles/login.module.css"
import Link from 'next/link'

export const metadata = {
    title: "Register age",
    description: 'Generated by kawsar firoz',
}


const page = () => {
  return (
      <div className={styles.login}>
          <h1 className={styles.loginheader}>SIGNUP</h1>

          <form action="" className={styles.loginForm}>
              <input type="text" placeholder='Username' required className={styles.input} />
              <input type="password" placeholder='password' required className={styles.input} />
              <input type="password" placeholder='password' required className={styles.input} />
              <button className={styles.loginbtn}>Register</button>
              <Link className={styles.loginLink} href="/login">Already have an account ? <b>SIGNIN </b></Link>
          </form>
      </div>
  )
}

export default page